"use client";

import React, { useState, useEffect } from 'react';
import { authClient } from '@/lib/auth-client';
import { 
    BarChart, 
    Bar, 
    XAxis, 
    YAxis, 
    CartesianGrid, 
    Tooltip, 
    ResponsiveContainer 
} from 'recharts';
import { 
    BarChartIcon, 
    HomeIcon, 
    CalendarIcon, 
    DownloadIcon,
    PersonIcon,
    DoubleArrowRightIcon
} from '@radix-ui/react-icons';
import { toast } from 'react-toastify';
import Link from 'next/link';

export default function AdminOverview() {
    const { data: session } = authClient.useSession();
    const [analytics, setAnalytics] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchAnalytics = async () => {
            try {
                const token = localStorage.getItem('jwt-token');
                const res = await fetch(`${process.env.NEXT_PUBLIC_SERVER_URL}/admin/analytics`, {
                    headers: {
                        'Authorization': `Bearer ${token}`
                    }
                });
                const data = await res.json();
                if (data && !data.error) {
                    setAnalytics(data);
                } else {
                    toast.error("Failed to load admin analytics.");
                }
            } catch (err) {
                console.error("Error fetching admin analytics:", err);
            } finally {
                setLoading(false);
            }
        };
        fetchAnalytics();
    }, [session]);

    const handleDownloadReport = () => {
        window.print();
    };

    if (loading) {
        return (
            <div className="w-full min-h-[50vh] flex flex-col justify-center items-center">
                <span className="loading loading-spinner loading-md text-[#319795]"></span>
                <p className="text-xs text-slate-400 mt-2 font-bold uppercase tracking-wider">Loading administrative overview...</p>
            </div>
        );
    }

    const {
        totalUsers,
        tenantCount,
        ownerCount,
        adminCount,
        totalProperties,
        approvedProperties,
        pendingProperties,
        rejectedProperties,
        totalBookings,
        totalTransactions,
        totalRevenue,
        chartData
    } = analytics || {
        totalUsers: 0,
        tenantCount: 0,
        ownerCount: 0,
        adminCount: 0,
        totalProperties: 0,
        approvedProperties: 0,
        pendingProperties: 0,
        rejectedProperties: 0,
        totalBookings: 0,
        totalTransactions: 0,
        totalRevenue: 0,
        chartData: []
    };

    return (
        <div className="space-y-8 print:bg-white print:p-8">
            {/* Header section */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 print:hidden">
                <div>
                    <h1 className="text-2xl sm:text-3xl font-black text-[#0A192F] tracking-tight antialiased">
                        System Admin Overview
                    </h1>
                    <p className="text-slate-400 text-xs font-semibold uppercase tracking-wider mt-1">
                        High-level dashboard overview of platform operations and financials
                    </p>
                </div>
                <button 
                    onClick={handleDownloadReport}
                    className="btn btn-md bg-[#319795] hover:bg-[#277a78] border-none text-white font-bold rounded-xl normal-case flex items-center gap-2 shadow-sm shrink-0"
                >
                    <DownloadIcon className="w-4 h-4" />
                    <span>Download Platform Report</span>
                </button>
            </div>

            {/* Printable Header */}
            <div className="hidden print:block border-b-2 border-slate-800 pb-6 mb-8">
                <h1 className="text-3xl font-black text-[#0A192F]">DreamPlot Platform Financial & Operational Report</h1>
                <p className="text-slate-500 text-sm mt-1">Generated by System Administrator: {session?.user?.name}</p>
                <p className="text-slate-400 text-xs mt-1">Report date: {new Date().toLocaleDateString()} {new Date().toLocaleTimeString()}</p>
            </div>

            {/* Metric Grid Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                {/* Revenue card */}
                <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm flex items-center gap-5">
                    <div className="w-12 h-12 rounded-2xl bg-indigo-50 flex items-center justify-center text-indigo-600">
                        <BarChartIcon className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Total Revenue</p>
                        <h2 className="text-2xl font-black text-[#0A192F] mt-1">${totalRevenue.toLocaleString()}</h2>
                    </div>
                </div>

                {/* Users card */}
                <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm flex items-center gap-5">
                    <div className="w-12 h-12 rounded-2xl bg-blue-50 flex items-center justify-center text-blue-600">
                        <PersonIcon className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Total Users</p>
                        <h2 className="text-2xl font-black text-[#0A192F] mt-1">{totalUsers}</h2>
                    </div>
                </div>

                {/* Properties card */}
                <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm flex items-center gap-5">
                    <div className="w-12 h-12 rounded-2xl bg-teal-50 flex items-center justify-center text-[#319795]">
                        <HomeIcon className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Total Properties</p>
                        <h2 className="text-2xl font-black text-[#0A192F] mt-1">{totalProperties}</h2>
                    </div>
                </div>

                {/* Bookings card */}
                <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm flex items-center gap-5">
                    <div className="w-12 h-12 rounded-2xl bg-yellow-50 flex items-center justify-center text-yellow-600">
                        <CalendarIcon className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Total Bookings</p>
                        <h2 className="text-2xl font-black text-[#0A192F] mt-1">{totalBookings}</h2>
                    </div>
                </div>
            </div>

            {/* Chart and distribution panels */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Revenue chart */}
                <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm lg:col-span-2 space-y-6">
                    <div>
                        <h3 className="text-base font-bold text-[#0A192F]">Platform Revenue History</h3>
                        <p className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Total monthly system transaction volumes (Last 12 Months)</p>
                    </div>
                    <div className="w-full h-72">
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0" />
                                <XAxis dataKey="month" stroke="#A0AEC0" fontSize={10} fontWeight="bold" tickLine={false} />
                                <YAxis stroke="#A0AEC0" fontSize={10} fontWeight="bold" tickFormatter={(v) => `$${v}`} tickLine={false} axisLine={false} />
                                <Tooltip 
                                    contentStyle={{ backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: '12px', fontSize: '12px', fontWeight: 'bold' }}
                                    formatter={(v) => [`$${v.toLocaleString()}`, "Revenue"]}
                                />
                                <Bar dataKey="revenue" fill="#319795" radius={[4, 4, 0, 0]} />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* System Distributions */}
                <div className="bg-white border border-slate-200 rounded-3xl p-6 shadow-sm space-y-6 flex flex-col justify-between">
                    <div>
                        <h3 className="text-base font-bold text-[#0A192F]">Platform Demographics</h3>
                        <p className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">User roles & Listings Moderation ratios</p>
                    </div>

                    {/* Role ratios */}
                    <div className="space-y-3">
                        <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider">User Breakdown</h4>
                        <div className="space-y-2">
                            {/* Tenants */}
                            <div>
                                <div className="flex justify-between text-xs font-semibold mb-1">
                                    <span className="text-slate-600">Tenants</span>
                                    <span className="text-slate-800">{tenantCount} ({totalUsers > 0 ? Math.round((tenantCount / totalUsers) * 100) : 0}%)</span>
                                </div>
                                <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
                                    <div className="h-full bg-blue-500" style={{ width: `${totalUsers > 0 ? (tenantCount / totalUsers) * 100 : 0}%` }} />
                                </div>
                            </div>
                            {/* Owners */}
                            <div>
                                <div className="flex justify-between text-xs font-semibold mb-1">
                                    <span className="text-slate-600">Owners</span>
                                    <span className="text-slate-800">{ownerCount} ({totalUsers > 0 ? Math.round((ownerCount / totalUsers) * 100) : 0}%)</span>
                                </div>
                                <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
                                    <div className="h-full bg-teal-500" style={{ width: `${totalUsers > 0 ? (ownerCount / totalUsers) * 100 : 0}%` }} />
                                </div>
                            </div>
                            {/* Admins */}
                            <div>
                                <div className="flex justify-between text-xs font-semibold mb-1">
                                    <span className="text-slate-600">Administrators</span>
                                    <span className="text-slate-800">{adminCount} ({totalUsers > 0 ? Math.round((adminCount / totalUsers) * 100) : 0}%)</span>
                                </div>
                                <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
                                    <div className="h-full bg-indigo-500" style={{ width: `${totalUsers > 0 ? (adminCount / totalUsers) * 100 : 0}%` }} />
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Listings status */}
                    <div className="space-y-3 border-t border-slate-100 pt-4">
                        <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider">Property Listings Approval</h4>
                        <div className="grid grid-cols-3 gap-2 text-center">
                            <div className="bg-emerald-50 rounded-xl p-2.5 border border-emerald-100/50">
                                <span className="text-emerald-700 font-extrabold text-sm block">{approvedProperties}</span>
                                <span className="text-[10px] font-bold text-emerald-600 uppercase tracking-wider">Approved</span>
                            </div>
                            <div className="bg-amber-50 rounded-xl p-2.5 border border-amber-100/50">
                                <span className="text-amber-700 font-extrabold text-sm block">{pendingProperties}</span>
                                <span className="text-[10px] font-bold text-amber-600 uppercase tracking-wider">Pending</span>
                            </div>
                            <div className="bg-rose-50 rounded-xl p-2.5 border border-rose-100/50">
                                <span className="text-rose-700 font-extrabold text-sm block">{rejectedProperties}</span>
                                <span className="text-[10px] font-bold text-rose-600 uppercase tracking-wider">Rejected</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Quick shortcuts */}
            <div className="bg-slate-50 border border-slate-200/80 rounded-3xl p-6 print:hidden flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                    <h3 className="text-sm font-bold text-slate-700">Need to moderate user lists or review property applications?</h3>
                    <p className="text-xs text-slate-400 font-medium">Use the operations shortcuts to access role lists and active transactions audit log.</p>
                </div>
                <div className="flex gap-2">
                    <Link href="/dashboard/admin/users" className="btn btn-sm btn-outline border-slate-300 text-slate-700 rounded-xl hover:bg-slate-100 normal-case font-bold flex items-center gap-1.5 h-10 min-h-0">
                        <span>All Users Directory</span>
                        <DoubleArrowRightIcon className="w-3 h-3" />
                    </Link>
                    <Link href="/dashboard/admin/properties" className="btn btn-sm bg-black hover:bg-slate-900 border-none text-white rounded-xl normal-case font-bold flex items-center gap-1.5 h-10 min-h-0">
                        <span>Moderate Listings</span>
                        <DoubleArrowRightIcon className="w-3 h-3" />
                    </Link>
                </div>
            </div>

            {/* Print Footer */}
            <div className="hidden print:block pt-12 text-center text-xs text-slate-400 border-t border-slate-200 mt-20">
                DreamPlot Platform Operations. Highly Confidential.
            </div>
        </div>
    );
}
